"use client";

import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { supabase } from '@/lib/supabase';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { BookOpen, Check, Headphones, Mic, Save, Send, RefreshCcw, ArrowLeft, LogOut, Volume2, Square } from 'lucide-react';
import { EXAM_VERSION, listening, reading, language, writingTasks, speakingTasks, teacherPrompts, objectiveSummary, emptyEvidence, emptyReview, draftNarrative, validateReview, domainNames, rubricHints, unanswered, type Evidence, type Item, type Review, type Rating } from '@/lib/felipe-assessment';

type Student = {id:string;first_name:string;active?:boolean};
type Session = {id:string;student_id:string;version:string;stage:number;revision:number;evidence:Evidence;status:'draft'|'submitted';updated_at:string;submitted_at:string|null};
type Material = {id:string;student_id:string;title:string;body:string;published:boolean};
type Space = {student_id:string;username:string;welcome:string;kind:'alice'|'felipe'};
const steps=['Preparação','Escuta','Leitura','Língua','Escrita e mediação','Fala e envio'];
const errorText=(e:unknown)=>e instanceof Error?e.message:typeof e==='object'&&e&&'message' in e?String(e.message):'Não foi possível concluir. Tente novamente.';
const date=(s:string)=>new Date(s).toLocaleString('pt-BR');
const inputClass='bg-[#06101d] border-white/15 text-base';
function Notice({children}:{children:React.ReactNode}){return children?<p role="status" className="my-4 rounded-xl border border-cyan-200/20 bg-cyan-200/10 p-4 text-sm leading-6">{children}</p>:null;}
function Labeled({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-2 text-sm"><span>{label}</span>{children}</label>;}

export function PasswordAccess({onAuthenticated}:{onAuthenticated:()=>void}){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{
  const clean=username.trim().toLowerCase();
  if(!/^[a-z0-9][a-z0-9._-]{2,29}$/.test(clean)) throw new Error('Confira seu usuário, sem espaços ou acentos.');
  const {error}=await supabase.auth.signInWithPassword({email:clean+'@students.fylab.invalid',password});
  if(error) throw new Error('Usuário ou senha inválidos, ou acesso temporariamente indisponível.');
  setPassword('');onAuthenticated();
 }catch(e){setMessage(errorText(e));}finally{setBusy(false);}}
 return <form onSubmit={login} className="space-y-5"><h2 className="text-2xl font-semibold">Entre no seu espaço</h2><Labeled label="Usuário"><Input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)} className={inputClass}/></Labeled><Labeled label="Senha"><Input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} className={inputClass}/></Labeled><Button disabled={busy} className="w-full">{busy?'Entrando…':'Entrar'}</Button><p className="text-sm text-slate-400">Esqueceu a senha? Peça ao professor para redefini-la.</p><Notice>{message}</Notice></form>;
}

export function IndividualStudentRouter({student,onSignOut,legacy}:{student:Student;onSignOut:()=>void;legacy:React.ReactNode}){
 const [space,setSpace]=useState<Space|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 useEffect(()=>{let alive=true;(async()=>{const {data,error}=await supabase.from('personal_spaces').select('*').eq('student_id',student.id).maybeSingle();if(!alive)return;
 if(error){setMessage('Não foi possível verificar seu espaço individual. Tente recarregar a página.');}else setSpace(data);setLoading(false);})();return()=>{alive=false;};},[student.id]);
 if(loading)return <p className="p-8">Abrindo seu espaço…</p>;
 if(message)return <div className="p-8"><Notice>{message}</Notice><Button onClick={()=>window.location.reload()}>Recarregar</Button></div>;
 return space&&space.kind!=='alice'?<FelipeStudent student={student} space={space} onSignOut={onSignOut}/>:legacy;
}

function FelipeStudent({student,space,onSignOut}:{student:Student;space:Space;onSignOut:()=>void}){
 const [session,setSession]=useState<Session|null>(null),[evidence,setEvidence]=useState<Evidence>(emptyEvidence),[stage,setStage]=useState(0);
 const [view,setView]=useState<'home'|'exams'|'lessons'|'exam'>('home'),[materials,setMaterials]=useState<Material[]>([]),[completed,setCompleted]=useState<string[]>([]),[review,setReview]=useState<Review|null>(null);
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(''),[saveStatus,setSaveStatus]=useState(''),[saving,setSaving]=useState(false),[recordBusy,setRecordBusy]=useState(false);
 const [partial,setPartial]=useState(false),[confirmSubmit,setConfirmSubmit]=useState(false);
 const sessionRef=useRef<Session|null>(null),current=useRef({evidence,stage}),queue=useRef<Promise<boolean>>(Promise.resolve(true)),mounted=useRef(true);
 current.current={evidence,stage};
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;window.speechSynthesis?.cancel();};},[]);
 const load=useCallback(async()=>{setLoading(true);setMessage('');try{
  const {data:row,error}=await supabase.from('felipe_sessions').select('*').eq('student_id',student.id).eq('version',EXAM_VERSION).maybeSingle();if(error)throw error;
  setSession(row);sessionRef.current=row;if(row){setEvidence({...emptyEvidence(),...row.evidence});setStage(row.stage);}
  const {data:ms,error:me}=await supabase.from('personal_materials').select('*').eq('student_id',student.id).order('created_at',{ascending:true});if(me)throw me;setMaterials(ms||[]);
  const {data:cs,error:ce}=await supabase.from('personal_completions').select('material_id');if(ce)throw ce;setCompleted((cs||[]).map(x=>x.material_id));
  if(row){const {data:rv,error:re}=await supabase.from('felipe_reviews').select('review').eq('session_id',row.id).eq('published',true).maybeSingle();if(re)throw re;setReview(rv?.review||null);}
 }catch(e){setMessage(errorText(e));}finally{setLoading(false);}},[student.id]);
 useEffect(()=>{void load();},[load]);
 async function start(){setSaving(true);setMessage('');try{
  if(!sessionRef.current){const {data,error}=await supabase.from('felipe_sessions').insert({student_id:student.id,version:EXAM_VERSION,evidence:emptyEvidence()}).select().single();if(error)throw error;sessionRef.current=data;setSession(data);setEvidence(emptyEvidence());setStage(0);}
  setView('exam');
 }catch(e){setMessage(errorText(e));}finally{setSaving(false);}}
 // Serialize saves and use revision compare-and-swap: a second device cannot silently overwrite a draft.
 const persist=useCallback((submit=false)=>{
  const snapshot=structuredClone(current.current);
  const task=async()=>{const row=sessionRef.current;if(!row||row.status==='submitted')return true;
   if(mounted.current){setSaving(true);setSaveStatus('Salvando…');}
   try{const {data,error}=await supabase.from('felipe_sessions').update({evidence:snapshot.evidence,stage:snapshot.stage,status:submit?'submitted':'draft'}).eq('id',row.id).eq('revision',row.revision).eq('status','draft').select().maybeSingle();if(error)throw error;
    if(!data)throw new Error('Este diagnóstico mudou em outro dispositivo. Copie respostas ainda não salvas e recarregue antes de continuar.');
    sessionRef.current=data;if(mounted.current){setSession(data);setSaveStatus(submit?'Enviado ao professor.':'Salvo no banco às '+new Date().toLocaleTimeString('pt-BR'));}return true;
   }catch(e){if(mounted.current){setSaveStatus('Não salvo — mantenha esta página aberta.');setMessage(errorText(e));}return false;
   }finally{if(mounted.current)setSaving(false);}
  };queue.current=queue.current.then(task,task);return queue.current;
 },[]);
 useEffect(()=>{if(!sessionRef.current||sessionRef.current.status==='submitted'||view!=='exam')return;setSaveStatus('Alterações pendentes…');const timer=setTimeout(()=>{void persist();},1000);return()=>clearTimeout(timer);},[evidence,stage,view,persist]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(view==='exam'&&sessionRef.current?.status==='draft'){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[view]);
 async function leave(){if(await persist()){setView('home');await load();}}
 async function submit(){if(!evidence.consent){setMessage('Confirme a autorização na preparação.');return;}if(await persist(true)){setView('home');setMessage('Respostas recebidas pelo banco e disponíveis ao professor. O parecer aparecerá após a revisão.');}}
 async function complete(m:Material){setMessage('');const {error}=await supabase.from('personal_completions').insert({material_id:m.id});if(error&&error.code!=='23505')setMessage(error.message);else setCompleted(old=>[...old,m.id]);}
 function patch(partial:Partial<Evidence>){setEvidence(old=>({...old,...partial}));}
 const incomplete=unanswered(evidence)+writingTasks.filter(t=>!evidence.texts[t.id]?.trim()).length+speakingTasks.filter(t=>!evidence.oral[t.id]?.path&&evidence.oral[t.id]?.mode!=='live').length;
 return <main className="felipe-space min-h-screen text-slate-100"><header className="border-b border-white/10"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-5 py-5"><div><p className="text-sm text-cyan-200">FYLAB Personal Classes</p><p className="font-semibold">Espaço de {student.first_name}</p></div><div className="flex gap-2">{view==='exam'?<Button variant="outline" disabled={saving||recordBusy} onClick={leave}><Save/>Salvar e pausar</Button>:<><Button variant="outline" onClick={load} disabled={loading}><RefreshCcw/>Atualizar</Button><Button variant="ghost" onClick={onSignOut}><LogOut/>Sair</Button></>}</div></div></header>
 <div className="mx-auto max-w-6xl px-5 py-8"><Notice>{message}</Notice>{view!=='exam'&&<nav aria-label="Área do aluno" className="mb-8 flex flex-wrap gap-3">{([['home','Início'],['exams','Exames'],['lessons','Lições']] as const).map(([key,label])=><Button key={key} variant={view===key?'default':'outline'} onClick={()=>setView(key)}>{label}</Button>)}</nav>}{loading?<p>Carregando dados…</p>:view!=='exam'?<>
  {view==='home'&&<><p className="eyebrow">Seu percurso individual</p><h1 className="portal-title">Olá, {student.first_name}.</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-300">{space.welcome} O ponto de partida é uma hipótese; suas respostas vão orientar o próximo passo.</p>
  <div className="my-8 grid gap-5 sm:grid-cols-2"><article className="exam-card"><h2 className="text-2xl font-semibold">Exames</h2><p className="my-4 text-slate-300">Seu diagnóstico, parecer e próximos passos.</p><Button onClick={()=>setView('exams')}>Abrir exames</Button></article><article className="exam-card"><h2 className="text-2xl font-semibold">Lições</h2><p className="my-4 text-slate-300">{completed.length} lições concluídas. Continue seu percurso.</p><Button onClick={()=>setView('lessons')}>Abrir lições</Button></article></div></>}
 {view==='exams'&&<><h1 className="portal-title">Meus exames</h1><div className="my-8 grid gap-5 md:grid-cols-[1.3fr_1fr]"><article className="exam-card"><Headphones className="text-cyan-200"/><h2 className="mt-4 text-2xl font-semibold">Seu inglês em contexto</h2><p className="my-4 leading-7 text-slate-300">Escuta, leitura, escrita, fala, interação e mediação. Tarefas de A2 a B2; previsão de 80–100 minutos, com pausas e conversa ao vivo com o professor.</p><p className="mb-5 text-sm text-cyan-200">{session?.status==='submitted'?(review?'Parecer publicado':'Enviado • aguardando revisão'):session?`Em andamento • ${steps[session.stage]}`:'Ainda não iniciado'}</p>{session?.status!=='submitted'&&<Button onClick={start} disabled={saving}>{session?'Continuar diagnóstico':'Iniciar diagnóstico'}</Button>}<p className="mt-4 text-sm text-slate-400">Sem nota global. Não é certificação de proficiência.</p></article><article className="exam-card"><BookOpen className="text-cyan-200"/><h2 className="mt-4 text-xl font-semibold">Próximos passos</h2><ol className="mt-4 list-decimal space-y-3 pl-5 text-base text-slate-300"><li>Faça as tarefas por conta própria.</li><li>Converse com o professor na etapa oral.</li><li>Receba seu perfil e o plano de aulas aqui.</li></ol></article></div>
  {review&&<article className="exam-card my-8"><p className="eyebrow">Revisado pelo professor</p><h2 className="my-4 text-2xl font-semibold">Seu parecer e plano</h2><p className="whitespace-pre-wrap leading-8">{review.narrative}</p><Button className="mt-5 print:hidden" onClick={()=>window.print()}>Salvar parecer em PDF</Button></article>}
  </>}{view==='lessons'&&<><h1 className="portal-title mb-5">Minhas lições</h1>{materials.length?materials.map(m=><article key={m.id} className="exam-card mb-4"><h3 className="text-xl font-medium">{m.title}</h3><p className="my-5 whitespace-pre-wrap leading-8 text-slate-300">{m.body}</p><Button onClick={()=>complete(m)} disabled={completed.includes(m.id)}>{completed.includes(m.id)?'Concluído':'Marcar como concluído'}</Button></article>):<p className="text-slate-400">O professor disponibilizará seus conteúdos após o diagnóstico.</p>}</>}
 </>:<>
  <div className="mb-6 flex flex-wrap gap-2" aria-label="Etapas">{steps.map((s,i)=><Button key={s} variant={i===stage?'default':'outline'} disabled={saving||recordBusy} onClick={async()=>{if(await persist()){setStage(i);window.speechSynthesis?.cancel();}}}>{i+1}. {s}</Button>)}</div><p className="mb-5 text-sm text-cyan-200" aria-live="polite">{saveStatus}</p>
  {stage===0&&<section className="exam-card space-y-5"><h1 className="text-3xl font-semibold">Antes de começar</h1><p className="leading-7">Não use tradutor, IA nem ajuda com respostas. Pode marcar “Não sei” ou registrar uma dificuldade. Não haverá cronômetro de encerramento. Faça uma pausa entre escrita e fala, se precisar.</p><Labeled label="Para que você quer usar inglês? Conte interesses e situações em que sente dificuldade (português ou inglês)."><Textarea className={inputClass} value={evidence.goals} onChange={e=>patch({goals:e.target.value})}/></Labeled>
  <label className="flex gap-3"><Checkbox checked={evidence.consent} onCheckedChange={v=>patch({consent:v===true})}/><span>Autorizo o registro das respostas para acompanhamento pedagógico. Se sou menor de idade, meu responsável autorizou.</span></label>
  <label className="flex gap-3"><Checkbox checked={evidence.audioConsent} onCheckedChange={v=>patch({audioConsent:v===true})}/><span>Autorizo também guardar as gravações de voz em área privada para revisão pelo professor. Opcional: sem gravação, a fala deve ser avaliada ao vivo.</span></label>
  <p className="text-sm text-slate-400">As respostas ficam no Supabase, acessíveis à sua conta e ao professor. Não inclua endereço, telefone ou outros dados pessoais. Peça ao professor a exclusão das gravações quando não forem mais necessárias. A síntese de voz e o microfone dependem do seu navegador.</p>
  <Button variant="outline" onClick={()=>{if(!window.speechSynthesis){setMessage('Áudio indisponível. Combine a leitura dos textos pelo professor.');return;}const u=new SpeechSynthesisUtterance('This is a short audio test. Can you hear me clearly?');u.lang='en-US';window.speechSynthesis.speak(u);}}>Testar áudio</Button>
  <Labeled label="Problemas técnicos, adaptações ou ajuda recebida"><Textarea className={inputClass} value={evidence.technical} onChange={e=>patch({technical:e.target.value})}/></Labeled></section>}
  {stage===1&&<section><h1 className="text-3xl font-semibold">Listen for meaning</h1><p className="my-4 leading-7 text-slate-300">Ouça cada mensagem até duas vezes como condição inicial. Repetições adicionais são possíveis e serão registradas. Se o áudio não funcionar, combine a leitura com o professor e registre em Preparação.</p>{listening.map(p=><article key={p.id} className="exam-card my-5"><h2 className="text-xl font-semibold">{p.title}</h2><Button className="my-4" onClick={()=>{if(!window.speechSynthesis){setMessage('Síntese de voz indisponível. Peça a leitura ao professor.');return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(p.text);u.lang='en-US';u.rate=1;u.onstart=()=>setEvidence(old=>({...old,plays:{...old.plays,[p.id]:(old.plays[p.id]||0)+1}}));u.onerror=()=>setMessage('Falha no áudio. Registre a ocorrência e combine alternativa com o professor.');window.speechSynthesis.speak(u);}}><Volume2/>Ouvir ({evidence.plays[p.id]||0} reproduções)</Button>{p.items.map(q=><Question key={q.id} q={q} value={evidence.answers[q.id]} onChange={v=>setEvidence(old=>({...old,answers:{...old.answers,[q.id]:v}}))}/>)}</article>)}</section>}
  {stage===2&&<section><h1 className="text-3xl font-semibold">Read beyond the words</h1>{reading.map(p=><article key={p.id} className="exam-card my-5"><h2 className="text-xl font-semibold">{p.title}</h2><blockquote lang="en" className="my-6 whitespace-pre-wrap border-l-2 border-cyan-200 pl-5 text-base leading-8 text-slate-200">{p.text}</blockquote>{p.items.map(q=><Question key={q.id} q={q} value={evidence.answers[q.id]} onChange={v=>setEvidence(old=>({...old,answers:{...old.answers,[q.id]:v}}))}/>)}</article>)}</section>}
  {stage===3&&<section className="exam-card"><h1 className="mb-5 text-3xl font-semibold">Language in use</h1><p className="text-slate-300">Este bloco ajuda a localizar lacunas. Não define sozinho seu nível.</p>{language.map(q=><Question key={q.id} q={q} value={evidence.answers[q.id]} onChange={v=>setEvidence(old=>({...old,answers:{...old.answers,[q.id]:v}}))}/>)}</section>}
  {stage===4&&<section><h1 className="text-3xl font-semibold">Write, explain, connect</h1><p className="my-4 text-slate-300">Escreva sem tradutor ou IA. Desative sugestões automáticas de texto, se possível, ou registre o uso em Preparação.</p>{writingTasks.map(t=><article className="exam-card my-5" key={t.id}><p className="text-sm text-cyan-200">{t.target}</p><h2 className="my-3 text-xl font-semibold">{t.title}</h2><p lang="en" className="whitespace-pre-wrap leading-8">{t.prompt}</p><p className="my-4 text-sm text-slate-400">{t.guide}</p><Labeled label="Sua resposta"><Textarea lang="en" spellCheck={false} autoComplete="off" className={inputClass+' min-h-60 leading-8'} value={evidence.texts[t.id]||''} onChange={e=>setEvidence(old=>({...old,texts:{...old.texts,[t.id]:e.target.value}}))}/></Labeled><p className="mt-3 text-sm text-slate-400">{(evidence.texts[t.id]||'').trim().split(/\s+/).filter(Boolean).length} palavras • extensão não é nota.</p></article>)}</section>}
  {stage===5&&<section><h1 className="text-3xl font-semibold">Let’s talk</h1><p className="my-4 leading-7 text-slate-300">Faça com o professor na aula online. Ele avalia fluência, inteligibilidade, autonomia e como você reage à conversa. Texto digitado não substitui uma amostra oral.</p>{speakingTasks.map((t,i)=><article className="exam-card my-5" key={t.id}><p className="text-sm text-cyan-200">{t.target}</p><h2 className="my-3 text-xl font-semibold">{t.title}</h2><p lang="en" className="leading-8">{t.prompt}</p><p className="my-4 text-sm text-slate-400">{t.guide}</p><VoiceTask key={t.id} studentId={student.id} sessionId={session!.id} task={t.id} disabled={recordBusy} consent={evidence.audioConsent} path={evidence.oral[t.id]?.path} persist={persist} onBusy={setRecordBusy} onError={setMessage} onSaved={path=>setEvidence(old=>({...old,oral:{...old.oral,[t.id]:{...old.oral[t.id],path,mode:'recorded'}}}))}/>
  <label className="mt-5 flex gap-3"><Checkbox checked={evidence.oral[t.id]?.mode==='live'} onCheckedChange={v=>setEvidence(old=>({...old,oral:{...old.oral,[t.id]:{...old.oral[t.id],mode:v===true?'live':'pending'}}}))}/><span>{i===2?'Realizei a conversa com o professor ao vivo.':'Apresentei minha resposta oralmente ao professor, sem gravação.'}</span></label><Labeled label="Observação sobre esta tarefa (opcional)"><Textarea className={inputClass+' mt-3'} value={evidence.oral[t.id]?.note||''} onChange={e=>setEvidence(old=>({...old,oral:{...old.oral,[t.id]:{...old.oral[t.id],note:e.target.value}}}))}/></Labeled></article>)}
  <article className="exam-card space-y-5"><h2 className="text-2xl font-semibold">Enviar para análise do professor</h2><p>{incomplete?`${incomplete} tarefas sem resposta ou sem amostra oral indicada. Você pode voltar ou enviar um perfil parcial.`:'Todas as tarefas têm resposta ou uma modalidade oral indicada.'}</p>{incomplete>0&&<label className="flex gap-3"><Checkbox checked={partial} onCheckedChange={v=>setPartial(v===true)}/><span>Quero enviar mesmo com lacunas; registrei o motivo em Preparação.</span></label>}<label className="flex gap-3"><Checkbox checked={confirmSubmit} onCheckedChange={v=>setConfirmSubmit(v===true)}/><span>Conferi minhas respostas. Após enviar, elas ficarão preservadas para revisão.</span></label><Button disabled={saving||recordBusy||!evidence.consent||!confirmSubmit||(incomplete>0&&!partial)} onClick={submit}><Send/>Enviar diagnóstico</Button><p className="text-sm text-slate-400">O envio só será confirmado após o banco receber. O professor publicará o texto final, sem nota numérica.</p></article></section>}
  <footer className="mt-8 flex flex-wrap justify-between gap-3 print:hidden"><Button variant="outline" disabled={saving||recordBusy||stage===0} onClick={()=>{window.speechSynthesis?.cancel();setStage(s=>s-1);}}><ArrowLeft/>Anterior</Button><Button variant="outline" disabled={saving||recordBusy} onClick={()=>persist()}><Save/>Salvar agora</Button>{stage<5&&<Button disabled={saving||recordBusy} onClick={async()=>{if(await persist()){window.speechSynthesis?.cancel();setStage(s=>s+1);window.scrollTo(0,0);}}}>Próxima etapa</Button>}</footer>
 </>}</div></main>;
}

function Question({q,value,onChange}:{q:Item;value?:string;onChange:(v:string)=>void}){return <fieldset className="my-7 border-t border-white/10 pt-5"><legend className="mb-3 text-base font-medium" lang="en">{q.question}</legend><RadioGroup value={value||''} onValueChange={onChange}>{[...q.options,'Não sei / prefiro não responder'].map((o,i)=><label key={i} className="option-row !text-base"><RadioGroupItem value={String(i)}/><span>{o}</span></label>)}</RadioGroup></fieldset>;}

function VoiceTask({studentId,sessionId,task,consent,path,persist,onSaved,onError,onBusy,disabled}:{disabled:boolean;studentId:string;sessionId:string;task:string;consent:boolean;path?:string;persist:()=>Promise<boolean>;onSaved:(path:string)=>void;onError:(v:string)=>void;onBusy:(v:boolean)=>void}){
 const [recording,setRecording]=useState(false),[blob,setBlob]=useState<Blob|null>(null),[localUrl,setLocalUrl]=useState(''),[busy,setBusy]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 useEffect(()=>{if(!blob)return;const url=URL.createObjectURL(blob);setLocalUrl(url);return()=>URL.revokeObjectURL(url);},[blob]);
 async function record(){setBusy(true);onBusy(true);onError('');try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Gravação não disponível. Faça a tarefa ao vivo com o professor.');
  const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;const types=['audio/webm','audio/mp4','audio/ogg'];const mime=types.find(t=>MediaRecorder.isTypeSupported(t));const rec=new MediaRecorder(s,mime?{mimeType:mime}:undefined);recorder.current=rec;const chunks:Blob[]=[];
  rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onstop=()=>{s.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current);if(alive.current){setBlob(new Blob(chunks,{type:rec.mimeType.split(';')[0]||'audio/webm'}));setRecording(false);onBusy(false);}};
  rec.start();setRecording(true);onBusy(true);timer.current=setTimeout(()=>{if(rec.state==='recording')rec.stop();},6*60*1000);
 }catch(e){stream.current?.getTracks().forEach(t=>t.stop());onError(errorText(e));onBusy(false);}finally{setBusy(false);}}
 async function upload(){if(!blob)return;setBusy(true);onBusy(true);onError('');try{if(blob.size>15*1024*1024)throw new Error('Áudio maior que 15 MB. Grave uma resposta mais curta ou faça ao vivo.');if(!await persist())throw new Error('Salve a autorização antes de enviar o áudio.');
  const ext=blob.type.includes('mp4')?'mp4':blob.type.includes('ogg')?'ogg':'webm';const dest=`${studentId}/${sessionId}/${task}-${crypto.randomUUID()}.${ext}`;
  const {error}=await supabase.storage.from('felipe-audio').upload(dest,blob,{contentType:blob.type,upsert:false});if(error)throw error;onSaved(dest);setBlob(null);setLocalUrl('');
 }catch(e){onError(errorText(e));}finally{setBusy(false);onBusy(false);}}
 return <div className="space-y-4"><div className="flex flex-wrap gap-3"><Button disabled={!consent||busy||(disabled&&!recording)} variant="outline" onClick={()=>recording?recorder.current?.stop():record()}>{recording?<Square/>:<Mic/>}{recording?'Parar gravação':'Gravar resposta'}</Button>{blob&&!recording&&<Button onClick={upload} disabled={busy||disabled||!consent}>{busy?'Enviando áudio…':'Guardar gravação privada'}</Button>}</div>{!consent&&<p className="text-sm text-slate-400">Sem autorização para guardar áudio. Use a avaliação ao vivo ou autorize na Preparação.</p>}{blob&&!recording&&<p className="text-sm text-amber-200">Este áudio ainda está somente neste dispositivo. Clique em Guardar gravação privada antes de sair da etapa.</p>}{localUrl&&<audio controls src={localUrl} className="max-w-full"/>}{path&&<p className="text-sm text-emerald-200">Gravação enviada. Salve as respostas para vincular esta amostra.</p>}</div>;
}

export function PersonalTeacher({students,refresh,mode='accounts'}:{students:Student[];refresh:()=>Promise<void>;mode?:'accounts'|'exams'|'lessons'}){
 const [spaces,setSpaces]=useState<Space[]>([]),[sessions,setSessions]=useState<Session[]>([]),[selected,setSelected]=useState(''),[materials,setMaterials]=useState<Material[]>([]),[done,setDone]=useState<string[]>([]);
 const [kind,setKind]=useState<'alice'|'felipe'>('alice');
 const [name,setName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[existing,setExisting]=useState(''),[consent,setConsent]=useState(false);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[publish,setPublish]=useState(false);
 const load=useCallback(async()=>{const [s,x,m,c]=await Promise.all([supabase.from('personal_spaces').select('*').order('created_at'),supabase.from('felipe_sessions').select('*').order('updated_at',{ascending:false}),supabase.from('personal_materials').select('*').order('created_at'),supabase.from('personal_completions').select('*')]);const error=s.error||x.error||m.error||c.error;if(error){setMessage('A área individual ainda não foi ativada no banco, ou está indisponível: '+error.message);return;}setSpaces(s.data||[]);setSessions(x.data||[]);setMaterials(m.data||[]);setDone((c.data||[]).map(v=>v.material_id));setSelected(old=>old||s.data?.[0]?.student_id||'');},[]);
 useEffect(()=>{void load();const timer=setInterval(()=>{void load();},10000);return()=>clearInterval(timer);},[load]);
 async function manage(action:'create'|'reset'){setBusy(true);setMessage('');try{
  const {data,error}=await supabase.functions.invoke('manage-personal-student',{body:{action,name,username,password,consent,kind,existingId:existing||null,studentId:selected}});
  if(error){let detail='';if('context' in error&&error.context instanceof Response){try{detail=(await error.context.json()).error||'';}catch{}}throw new Error(detail||'Não foi possível acessar o cadastro seguro. Confira a Edge Function e sua sessão de professor.');}if(data?.error)throw new Error(data.error);
  setPassword('');setConsent(false);setMessage(action==='create'?'Conta criada. Envie o usuário e a senha por um canal privado. A senha não será exibida aqui.':'Senha redefinida. Comunique a nova senha em privado.');await load();await refresh();
 }catch(e){setMessage(errorText(e));}finally{setBusy(false);}}
 async function add(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');const {error}=await supabase.from('personal_materials').insert({student_id:selected,title,body,published:publish});if(error)setMessage(error.message);else{setTitle('');setBody('');setPublish(false);await load();}setBusy(false);}
 const activeStudent=students.find(s=>s.id===selected),activeSession=sessions.find(s=>s.student_id===selected),space=spaces.find(s=>s.student_id===selected);
 return <section className="felipe-space space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Acompanhamento individual</p><h1 className="portal-title">{mode==='accounts'?'Alunos e acessos':mode==='exams'?'Exames individuais':'Lições individuais'}</h1><p className="mt-4 text-base text-slate-300">Cadastro, diagnóstico, revisão e materiais ligados ao mesmo aluno.</p></div><Button variant="outline" onClick={load}><RefreshCcw/>Atualizar dados</Button></div><Notice>{message}</Notice>
 {mode==='accounts'&&<details className="exam-card" open><summary className="cursor-pointer text-xl font-semibold">Criar acesso com usuário e senha</summary><form onSubmit={e=>{e.preventDefault();void manage('create');}} className="mt-5 grid gap-5 md:grid-cols-2"><Labeled label="Cadastro existente (opcional)"><select className={inputClass+' w-full rounded-lg border p-3'} value={existing} onChange={e=>{setExisting(e.target.value);const s=students.find(x=>x.id===e.target.value);if(s){setName(s.first_name);setUsername(s.first_name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,''));setKind(s.first_name.toLowerCase()==='felipe'?'felipe':'alice');}}}><option value="">Criar aluno novo</option>{students.filter(s=>!spaces.some(p=>p.student_id===s.id)).map(s=><option key={s.id} value={s.id}>{s.first_name}</option>)}</select></Labeled><Labeled label="Exame e percurso"><select value={kind} onChange={e=>setKind(e.target.value as 'alice'|'felipe')} className={inputClass+' w-full rounded-lg border p-3'}><option value="alice">A1–A2 • percurso da Alice</option><option value="felipe">A2–B2 • percurso do Felipe</option></select></Labeled><Labeled label="Nome do aluno"><Input required maxLength={60} value={name} onChange={e=>setName(e.target.value)} className={inputClass}/></Labeled><Labeled label="Usuário (3–30 caracteres, sem acentos)"><Input required autoComplete="off" pattern="[a-z0-9][a-z0-9._-]{2,29}" value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} className={inputClass}/></Labeled><Labeled label="Senha inicial (mínimo 10 caracteres)"><Input required type="password" minLength={10} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className={inputClass}/></Labeled><label className="flex gap-3 md:col-span-2"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>O aluno autorizou o uso pedagógico dos dados; se menor de idade, seu responsável autorizou.</span></label><Button disabled={busy||!consent}>Criar e vincular área individual</Button><p className="text-sm leading-6 text-slate-400">Selecionar um cadastro existente preserva seu histórico, mas substitui o acesso por código. Use esta opção apenas para o aluno correto.</p></form></details>}
 {spaces.length>0&&<><Labeled label="Aluno da área individual"><select className={inputClass+' w-full rounded-lg border p-3'} value={selected} onChange={e=>setSelected(e.target.value)}>{spaces.map(s=><option key={s.student_id} value={s.student_id}>{students.find(x=>x.id===s.student_id)?.first_name||s.username} • {s.username}</option>)}</select></Labeled>
 {mode==='accounts'&&<div className="grid gap-5 md:grid-cols-2"><article className="exam-card"><h2 className="text-xl font-semibold">Acesso de {activeStudent?.first_name}</h2><p className="my-4">{space?.kind==='alice'?'Percurso A1–A2 • exames na aba Exames':activeSession?activeSession.status==='draft'?`Em andamento • ${steps[activeSession.stage]}`:'Enviado para revisão':'Diagnóstico ainda não iniciado'}</p>{activeSession&&<p className="text-sm text-slate-400">Último salvamento: {date(activeSession.updated_at)}</p>}<p className="mt-3 text-sm">Usuário: {space?.username}. A senha não é armazenada nas tabelas do portal.</p></article><form className="exam-card space-y-4" onSubmit={e=>{e.preventDefault();void manage('reset');}}><h2 className="text-xl font-semibold">Redefinir senha</h2><Labeled label="Nova senha"><Input type="password" minLength={10} maxLength={128} required autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className={inputClass}/></Labeled><Button disabled={busy} variant="outline">Redefinir senha deste aluno</Button></form></div>}
 {mode==='exams'&&space?.kind==='alice'&&<Notice>As respostas deste percurso aparecem na lista de exames A1–A2 abaixo.</Notice>}
 {mode==='exams'&&space?.kind!=='alice'&&!activeSession&&<Notice>Este aluno ainda não iniciou o exame intermediário.</Notice>}
 {mode==='exams'&&activeSession&&<TeacherReview key={activeSession.id} session={activeSession} studentName={activeStudent?.first_name||'Felipe'}/>}
 {mode==='lessons'&&<><article className="exam-card"><h2 className="text-xl font-semibold">Lição só para {activeStudent?.first_name}</h2><form className="mt-5 space-y-4" onSubmit={add}><Labeled label="Título"><Input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} className={inputClass}/></Labeled><Labeled label="Conteúdo e orientações"><Textarea required maxLength={20000} value={body} onChange={e=>setBody(e.target.value)} className={inputClass+' min-h-44'}/></Labeled><label className="flex gap-3"><Checkbox checked={publish} onCheckedChange={v=>setPublish(v===true)}/><span>Publicar para este aluno</span></label><Button disabled={busy}>Salvar material individual</Button></form></article>
 {materials.filter(m=>m.student_id===selected).map(m=><article key={m.id} className="exam-card"><h3 className="text-xl font-medium">{m.title}</h3><p className="my-3 text-sm text-cyan-200">{m.published?'Publicado':'Rascunho'} • {done.includes(m.id)?'Concluído pelo aluno':'Ainda não concluído'}</p><p className="whitespace-pre-wrap leading-7">{m.body}</p><Button variant="outline" className="mt-4" onClick={async()=>{const {error}=await supabase.from('personal_materials').update({published:!m.published}).eq('id',m.id);if(error)setMessage(error.message);else await load();}}>{m.published?'Retirar publicação':'Publicar'}</Button></article>)}</>}</>}
 </section>;
}

function TeacherReview({session,studentName}:{session:Session;studentName:string}){
 const [review,setReview]=useState<Review>(emptyReview),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);
 const evidence={...emptyEvidence(),...session.evidence};
 useEffect(()=>{let alive=true;(async()=>{const {data,error}=await supabase.from('felipe_reviews').select('*').eq('session_id',session.id).maybeSingle();if(!alive)return;if(error)setMessage(error.message);else{if(data)setReview({...emptyReview(),...data.review,published:data.published});setReady(true);}})();return()=>{alive=false;};},[session.id]);
 function rating(domain:typeof domainNames[number],patch:Partial<Rating>){setReview(r=>({...r,ratings:{...r.ratings,[domain]:{...r.ratings[domain],...patch}}}));}
 async function save(publish:boolean){setMessage('');if(publish){const problem=validateReview(review);if(problem){setMessage(problem);return;}}setBusy(true);try{const next={...review,published:publish};const {error}=await supabase.from('felipe_reviews').upsert({session_id:session.id,review:next,published:publish,updated_at:new Date().toISOString()});if(error)throw error;setReview(next);setMessage(publish?'Parecer publicado na área do aluno.':'Rascunho salvo; ainda não visível ao aluno.');}catch(e){setMessage(errorText(e));}finally{setBusy(false);}}
 return <section className="space-y-5"><article className="exam-card"><h2 className="text-2xl font-semibold">Evidências do diagnóstico</h2><p className="mt-3 text-sm text-slate-400">Versão {session.version} • {session.status==='draft'?'Rascunho do aluno; aguarde o envio para publicar.':'Respostas preservadas após envio.'}</p><p className="my-4 whitespace-pre-wrap">Objetivos: {evidence.goals||'Ainda não registrados.'}</p><p className="mb-4 whitespace-pre-wrap">Condições informadas: {evidence.technical||'Nenhuma observação.'}</p>{objectiveSummary(evidence).map(s=><div key={s.name} className="my-4"><h3 className="font-semibold">{s.name}</h3><p className="mt-2 leading-7 text-slate-300">{s.details}</p></div>)}<p className="text-sm text-amber-200">Contagens para sua análise de itens, não nota ou conversão automática em CEFR. Os níveis indicam a demanda pretendida das tarefas, não calibração estatística.</p></article>
 <details className="exam-card"><summary className="cursor-pointer font-semibold">Gabarito, textos de escuta e respostas objetivas</summary>{[...listening,...reading].map(p=><div key={p.id} className="my-5"><h3 className="font-semibold">{p.title}</h3><p className="my-3 whitespace-pre-wrap leading-7">{p.text}</p>{p.id.startsWith('l')&&<p className="text-sm text-cyan-200">Reproduções registradas: {evidence.plays[p.id]||0}</p>}{p.items.map(q=><p className="my-3 text-sm leading-6" key={q.id}>{q.id} ({q.band}, {q.focus}): {q.question}<br/>Resposta: {q.options[Number(evidence.answers[q.id])]||'Sem resposta / não sei'}<br/>Esperada: {q.options[q.answer]}</p>)}</div>)}{language.map(q=><p key={q.id} className="my-3 text-sm">{q.id}: {q.question} — resposta: {q.options[Number(evidence.answers[q.id])]||'Sem resposta / não sei'}; esperada: {q.options[q.answer]}</p>)}</details>
 <article className="exam-card"><h2 className="text-xl font-semibold">Escrita e mediação</h2>{writingTasks.map(t=><div key={t.id} className="my-6"><h3 className="font-semibold">{t.title}</h3><details className="my-3 text-sm"><summary>Enunciado</summary><p className="whitespace-pre-wrap leading-7">{t.prompt}</p></details><blockquote className="whitespace-pre-wrap border-l-2 border-cyan-200 pl-5 leading-8">{evidence.texts[t.id]||'Ainda sem resposta.'}</blockquote></div>)}</article>
 <article className="exam-card"><h2 className="text-xl font-semibold">Condução e evidências orais</h2>{teacherPrompts.map(t=><p key={t} className="my-4 leading-7 text-slate-300">{t}</p>)}{speakingTasks.map(t=><div className="my-5 border-t border-white/10 pt-5" key={t.id}><h3 className="font-semibold">{t.title}</h3><p className="my-3 text-sm">Modalidade declarada: {evidence.oral[t.id]?.mode||'não informada'}. {evidence.oral[t.id]?.note}</p>{evidence.oral[t.id]?.path?<PrivateAudio path={evidence.oral[t.id].path!}/>:<p className="text-sm text-slate-400">Sem áudio guardado. Registre suas observações da aula ao vivo; não infira pronúncia de texto.</p>}</div>)}</article>
 <article className="exam-card space-y-5"><h2 className="text-2xl font-semibold">Sua avaliação por habilidade</h2><p className="leading-7 text-slate-300">Escolha o descritor mais bem sustentado, cite exemplos e diferencie desempenho independente de desempenho com apoio. A hipótese de nível intermediário não é um resultado.</p>{domainNames.map(domain=><fieldset key={domain} className="space-y-4 border-t border-white/10 pt-5"><legend className="text-xl font-medium">{domain}</legend><p className="text-sm leading-7 text-slate-400">{rubricHints[domain]}</p><Labeled label="Faixa estimada nesta amostra"><select className={inputClass+' w-full rounded-lg border p-3'} value={review.ratings[domain].band} onChange={e=>rating(domain,{band:e.target.value as Rating['band']})}>{['Não avaliado','Abaixo de A2 / investigar','A2','B1','B2','Acima de B2 / investigar'].map(b=><option key={b}>{b}</option>)}</select></Labeled><Labeled label="Evidências concretas, apoio necessário ou motivo da ausência"><Textarea className={inputClass} value={review.ratings[domain].evidence} onChange={e=>rating(domain,{evidence:e.target.value})}/></Labeled><Labeled label="Próximo passo desta habilidade"><Textarea className={inputClass} value={review.ratings[domain].next} onChange={e=>rating(domain,{next:e.target.value})}/></Labeled></fieldset>)}
 {(['conditions','strengths','priorities','plan'] as const).map((field,i)=><Labeled key={field} label={['Condições, apoio e confiabilidade da amostra','Pontos fortes','Prioridades pedagógicas','Plano das próximas aulas e quando reavaliar'][i]}><Textarea className={inputClass+' min-h-28'} value={review[field]} onChange={e=>setReview(r=>({...r,[field]:e.target.value}))}/></Labeled>)}
 <Button variant="outline" onClick={()=>setReview(r=>({...r,narrative:draftNarrative(studentName,r)}))}>Montar texto a partir das minhas observações</Button><Labeled label="Parecer final editável — sem nota"><Textarea className={inputClass+' min-h-80 leading-7'} value={review.narrative} onChange={e=>setReview(r=>({...r,narrative:e.target.value}))}/></Labeled><Notice>{message}</Notice><div className="flex flex-wrap gap-3"><Button variant="outline" disabled={!ready||busy||session.status!=='submitted'} onClick={()=>save(false)}><Save/>Salvar rascunho privado</Button><Button disabled={!ready||busy||session.status!=='submitted'} onClick={()=>save(true)}><Send/>Publicar parecer para o aluno</Button></div><p className="text-sm text-slate-400">{review.published?'Existe parecer publicado. Salvar como rascunho retira a publicação.':'Rascunho ainda não publicado.'}</p></article>
 </section>;
}

export function PersonalInbox({students,onOpen}:{students:Student[];onOpen:()=>void}){
 const [rows,setRows]=useState<{id:string;student_id:string;status:string;updated_at:string}[]>([]),[published,setPublished]=useState<string[]>([]),[message,setMessage]=useState('');
 const load=useCallback(async()=>{const [a,b]=await Promise.all([supabase.from('felipe_sessions').select('id,student_id,status,updated_at').order('updated_at',{ascending:false}),supabase.from('felipe_reviews').select('session_id').eq('published',true)]);if(a.error||b.error){setMessage('Área individual ainda não ativada ou indisponível.');return;}setMessage('');setRows(a.data||[]);setPublished((b.data||[]).map(x=>x.session_id));},[]);
 useEffect(()=>{void load();const timer=setInterval(()=>{void load();},10000);return()=>clearInterval(timer);},[load]);
 return <section className="exam-card mb-7 space-y-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold">Diagnósticos intermediários</h2><Button variant="outline" onClick={onOpen}>Abrir exames</Button></div><p className="text-sm text-slate-300">Acompanhe os envios e abra Exames para revisar as respostas.</p>{message&&<p role="status">{message}</p>}{rows.length?rows.map(r=><p key={r.id} className="text-base">{students.find(s=>s.id===r.student_id)?.first_name||'Aluno'} — {r.status==='draft'?'Em andamento':published.includes(r.id)?'Parecer publicado':'Enviado • aguarda revisão'} • {date(r.updated_at)}</p>):<p className="text-sm text-slate-400">Nenhum diagnóstico individual iniciado.</p>}<button className="text-sm text-cyan-200 underline" onClick={load}>Atualizar progresso</button></section>;
}

function PrivateAudio({path}:{path:string}){
 const [url,setUrl]=useState(''),[message,setMessage]=useState('');
 async function listen(){const {data,error}=await supabase.storage.from('felipe-audio').createSignedUrl(path,300);if(error)setMessage('Áudio não disponível: '+error.message);else{setUrl(data.signedUrl);setMessage('Link privado válido por cinco minutos.');}}
 async function remove(){if(!window.confirm('Excluir definitivamente esta gravação? As respostas e o parecer serão mantidos, mas o áudio não poderá ser recuperado.'))return;const {error}=await supabase.storage.from('felipe-audio').remove([path]);if(error)setMessage(error.message);else{setUrl('');setMessage('Gravação excluída definitivamente.');}}
 return <div className="space-y-3"><div className="flex gap-3"><Button variant="outline" onClick={listen}>Ouvir amostra privada</Button><Button variant="ghost" onClick={remove}>Excluir gravação</Button></div>{url&&<audio src={url} controls className="max-w-full"/>}<p className="text-sm text-slate-400">{message}</p></div>;
}
